name: Generate .deb app

on:
  workflow_dispatch:

jobs:
  create_deb_app:
    name: Create Deb App
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Generate linux app
        run: ./gradlew packageReleaseDeb

