name: Generate Dokka

on:
  workflow_dispatch:

jobs:
  generate_dokka:
    name: Generate Dokka
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '21'
      - name: Generate Dokka
        run: ./gradlew dokkaHtmlMultiModule --no-daemon
      - name: Upload Dokka
        uses: actions/upload-artifact@v4
        with:
          name: dokka
          path: build/dokka/htmlMultiModule/*

